### ISSUE TITLE
play函数在linux下不可用

### ISSUE THREAD

**Issue by fkxxyz** [Rainbow-Dreamer/musicpy#1]
play函数在linux下，会报错

```
In [8]: play(note('A',5))                                                                
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-8-e5677dd3da72> in <module>
----> 1 play(note('A',5))

~/.pyenv/versions/3.8.0/lib/python3.8/site-packages/musicpy/musicpy.py in play(chord1, tempo, track, channel, time1, track_num, name, modes)
    198                  track_num=1,
    199                  mode=modes)
--> 200     os.startfile(f'{name}.mid')
    201 
    202 

AttributeError: module 'os' has no attribute 'startfile'
```

但是在当前目录生成了个 temp.mid 能够播放。目测是 linux下的python没有 os.startfile 这个函数，仅仅windows才有，希望跨平台适配。

**Comment by fkxxyz** [comment]
另外，同为音乐爱好者，我最近也开发了个类似的程序，可以相互参考和交流奥 https://github.com/fkxxyz/simp-score

**Comment by Rainbow-Dreamer** [comment]
> play函数在linux下，会报错
> 
> ```
> In [8]: play(note('A',5))                                                                
> ---------------------------------------------------------------------------
> AttributeError                            Traceback (most recent call last)
> <ipython-input-8-e5677dd3da72> in <module>
> ----> 1 play(note('A',5))
> 
> ~/.pyenv/versions/3.8.0/lib/python3.8/site-packages/musicpy/musicpy.py in play(chord1, tempo, track, channel, time1, track_num, name, modes)
>     198                  track_num=1,
>     199                  mode=modes)
> --> 200     os.startfile(f'{name}.mid')
>     201 
>     202 
> 
> AttributeError: module 'os' has no attribute 'startfile'
> ```
> 
> 但是在当前目录生成了个 temp.mid 能够播放。目测是 linux下的python没有 os.startfile 这个函数，仅仅windows才有，希望跨平台适配。

好的，会去增加一下跨平台的支持。

**Comment by Rainbow-Dreamer** [comment]
> 另外，同为音乐爱好者，我最近也开发了个类似的程序，可以相互参考和交流奥 https://github.com/fkxxyz/simp-score

好的，我会关注这个项目，另外关于和弦的部分，我这个musicpy的库值得一提的是有一个智能判断任意一组音是什么和弦的算法，以及智能分离一首钢琴曲的主旋律和和弦部分的算法。这两个算法分别在detect函数和split_melody函数里，在musicpy.py文件里可以看到代码。

**Comment by Rainbow-Dreamer** [comment]
目前已经把musicpy里的play函数的跨平台支持写完了，目前支持windows/Linux/MacOs这几个系统。已经更新到github了，可以直接下载，我待会上传到PYPI。
