### ISSUE TITLE
Couldn't open /etc/timidity/freepats.cfg

### ISSUE THREAD

**Issue by bigshans** [Rainbow-Dreamer/musicpy#11]
Arch 下用 pip 安装， python 3.9 ，使用 play 函数就这样，
代码如下：
``` python
from musicpy import *
a = note('A', 5)
play(a)
```
报错：
```
/usr/lib/python3.9/site-packages/musicpy/musicpy.py in play(chord1, tempo, track, channel, time1, track_num, name, modes, instrument, i, save_as_file, deinterleave)
    235     if save_as_file:
    236         result_file = name
--> 237         pygame.mixer.music.load(result_file)
    238         pygame.mixer.music.play()
    239     else:

error: Couldn't open /etc/timidity/freepats.cfg
```
经过检查 /etc/timidity 这个目录没有，个人觉得这些文件可以直接放在包下的。

**Comment by Rainbow-Dreamer** [comment]
这个问题是只会在linux环境下才会遇到，在windows和mac都不会有这个问题，因为我自己的开发环境是windows，目前实在还没有精力兼容linux系统，所以很可能会有linux不兼容一些依赖库的问题出现，比如musicpy播放midi文件是使用pygame的midi模块，然而pygame在windows，mac和linux的版本都有些不一样，所以你在使用play函数播放音符的时候出现了问题。你issues里的同样的代码在我的windows电脑上完全可以正常运行的。至于解决办法，其实之前有个用linux的网友已经发了博客说怎么解决了，网址给你，https://www.codetd.com/article/12113460  你照着里面的做法就可以解决你的问题了。

**Comment by j3rryzh** [comment]
同样在arch linux下碰到一样的问题，我的系统是manjaro，安装了freepats-general-midi和timidity++这两个依赖之后解决问题。
