### ISSUE TITLE
音符滑音颤音功能

### ISSUE THREAD

**Issue by donmor** [Rainbow-Dreamer/musicpy#14]
比如增加滑音颤音的参数，接收lambda表达式（传入根据音符回放时间变化的量）或者数值

**Comment by Rainbow-Dreamer** [comment]
感谢您的提议，这些功能我本身也是有计划要加入的，在以后的版本我会陆续加入音符的滑音颤音功能，lambda函数调整以及可以加载实体音源插件以及音频文件的采样等功能，并且可以输出为音频文件。
