### ISSUE TITLE
实时变换tempo功能 / 音量问题

### ISSUE THREAD

**Issue by donmor** [Rainbow-Dreamer/musicpy#15]
能不能加入一种对象，可以像note一样插进一段chord里，其长度为0，作用是被处理到时更改后续序列的tempo，如果chord被打包进piece，则对整个piece生效，类似daw上的tempo轨那样

另外有个小问题，为什么musicpy的volume最高能设定到255？midi标准是到127的，做了一个包含大于127的音符的midi在fluidsynth播放缺音，提示超出127，导入musescore也是大面积缺音，但用java写的播放程序调用jvm自带的gervill就可以正常播放；如果把音符全改成127以下，fluidsynth正常播放，但声音很小，和手上一些其他的midi文件相比只有一半左右，这是什么情况？后续会修复吗？

**Comment by Rainbow-Dreamer** [comment]
改变tempo的功能我也是最近有计划加入的，因为也是对应着midi文件的tempo改变信息，这些逻辑去写一下就行了。

musicpy的volume是介于0~127之间的，也就是和midi文件的音符的音量范围一样，如果你设置一个音符音量为127，可以把play之后生成的midi文件放到编曲软件里看看，会看到音符的力度刚好是最大的。如果你设置了大于127的音量，128-255实际上是0-127的力度的重复，但是生成的midi文件可能会播放不出来音符，放到编曲软件里也读不出来音符，但是比如用pygame的mixer却可以正常播放这个midi文件，可能有的模块对midi音符的音量有更智能的转换，如果超过127到255之间，会减去127等价于0~127之间（只是个人猜测）。关于这个问题，我会在下一个新版本加入音量设定的范围限制，如果你设定超过127的音量我会让代码报错提示，这样应该就可以解决这个问题了。感谢你的反馈~

**Comment by Rainbow-Dreamer** [comment]
"如果把音符全改成127以下，fluidsynth正常播放，但声音很小，和手上一些其他的midi文件相比只有一半左右"这个问题我不太明白为什么，如果音符的音量设定都是0-127之间，那么写入的midi文件确实是对应midi文件里的标准音量0-127的，你可以试着打开一个编曲软件（比如FL Studio），把musicpy代码播放后生成的midi文件放进去，看看音符力度就可以确认musicpy的音符力度0-127是和midi文件的音符力度0-127一一对应的了，所以要么是fluidsynth有些问题，要么是你设定音量的语句写错了。我这里给你一个设定音符音量的例子，你自己运行试试看，
```python
a = chord('C,D,E')%(1/8,1/8)
a.setvolume([0,50,127])
play(a)
```
a有3个音，音量我依次设定为0,50,127,然后使用play函数播放，可以听到音量就是按照设定的来播放的，然后你把生成的midi文件temp.mid放到编曲软件里看看音符力度，会看到音符力度的显示都是正确的，我自己这边也确认过了。
