### ISSUE TITLE
mac 无法产生音效

### ISSUE THREAD

**Issue by zdYng** [Rainbow-Dreamer/musicpy#16]
运行测试demo，无法产生音效，只有‘dep’的声音

**Comment by Rainbow-Dreamer** [comment]
你好，因为在mac上musicpy的一些依赖库(比如pygame)不能与python的比较新的版本很好的兼容，之前经过我朋友的测试，在macOS上python 3.7.1是可以正常运行播放所有的musicpy的demo的（wiki我写的作曲示例代码），比 3.7.1更新的python的版本有很多都不行。请注意类似`/song`这样的写法是只有在我为musicpy写的编辑器里才可以运行的语法糖，如果是在python的IDE里运行musicpy代码的话，这里需要改成`play(song)`才可以正常运行，并且如果是在python的IDE里写musicpy，开头记得要先写`from musicpy import *`导入musicpy。

**Comment by arkilis** [comment]
请问作者何时可以支持3.7.1以上的版本？谢谢
