### ISSUE TITLE
chord类的setvolume方法，当ind参数设为'all'的时候，为什么要对self.notes进行note的类型检查？

### ISSUE THREAD

**Issue by DiamondI** [Rainbow-Dreamer/musicpy#18]
如题，在structures.py的1204行里有这样的语句：

```python
available_notes = [i for i in self.notes if type(i) == note]
```

根据上下文来看，这里的意思是，当`ind`参数设置为`all`以后，需要对`self.notes`里的每个内容进行类型检查，只有那些类型为`note`的对象才会被修改音量。但是`self.notes`应该在创建的时候就应该把输入转换成了 `note` 类型了，如果一定要做类型检查，也应该是在`self.notes`创建、新增的时候进行检查，而不应该在`setvolume`这样的方法里做检查。

另外，1199行`each = self.notes[current - 1]`中的`current`还没有进行初始化，假如`vol`类型为`int`，而`ind`类型为`list`，那么进入该分支则会报错。

**Comment by Rainbow-Dreamer** [comment]
您好，这里是因为在musicpy里，和弦类型的音符列表self.notes里面不只有音符类型，同时还有其他的乐理类型，速度变化类型(tempo)和弯音类型(pitch_bend)，这两个类型本身在定义上是没有音量的属性的，虽然我有内建一个音量的属性值，但是在初始化时是不可以传入的，只是会在初始化时内部默认给一个100的音量值，而且这两个类型本身也没有setvolume的方法。因此当ind为all的时候，如果你传入一个音量设置的列表，你基本上只会考虑音符列表里面是音符类型的音量，所以这时候过滤掉不是音符类型的乐理类型是必须的。1199行这里确实是我少写了一行current = ind[i]，感谢指正，我会去更新一下版本的。

**Comment by DiamondI** [comment]
既然是这样，那么在其它分支里是不是最好也做一下类型检查呢，如果`index`的位置不是一个`note`类型的话，可以抛出一个异常对用户进行警告，这样的话，用户会比较清楚哪些操作是合法的，哪些操作是非法的，以及非法的操作出现在什么地方。

此外，我发现代码里很多应该有限制的类型都没有及时做**类型检查**，比如说`note`类型的`volume`属性，根据wiki文档，它的范围应该在`[0, 127]`，而且实际使用的时候，发现它限制为整型。但是这些都没有在`note`类里面做检查，一直到调用midi了才开始报错，这对于使用这个库的用户来说不是很友好。一般来说，能在这个库里抛出的异常，最好都不要丢给依赖库，不然出现问题的时候，很难找源头。

如果这方面需要改进的话，很乐意贡献一点绵薄之力:smile:

**Comment by Rainbow-Dreamer** [comment]
和弦类型的setvolume函数的所有分支我都有进行类型检查的，您可以仔细看看，`if type(each) == note`这一句就是是否为音符类型的类型检查。关于volume的范围，按照midi的通用标准来说是0到127之间的任意整数(包括0和127)，确实是整型的，我在wiki上写的volume的范围是0~127，表达的就是这个意思，并不是[0, 127]，您可能看错了，我待会在wiki把volume的范围改成0到127之间的任意整数(包括0和127)应该会让大家更清楚。如果volume传入的是非整型的数值，我这边会直接取整，避免出现异常。
