### ISSUE TITLE
【提议】建议将当前原有的Readme内容整理到Wiki中。

### ISSUE THREAD

**Issue by LamGC** [Rainbow-Dreamer/musicpy#2]
可以将当前 Readme 的内容整理到 Wiki 作为项目的 **Quick Start** 文档供他人查阅，Readme 可以讲述项目的安装、使用和贡献项目的方法。
合理编写 Readme 将有助于其他人使用，甚至是贡献项目！**:D**

**Comment by LamGC** [comment]
尝试将 Readme 按照Markdown的语法整理了一下（然后参照了一下[中文文档指北](https://github.com/sparanoid/chinese-copywriting-guidelines)，不过没有详细检查规范）。
[musicpy-QuickStart.zip](https://github.com/Rainbow-Dreamer/musicpy/files/5055874/musicpy-QuickStart.zip)
（Github不支持Markdown文件上传，只能先打包了w）

**Comment by Rainbow-Dreamer** [comment]
> 尝试将 Readme 按照Markdown的语法整理了一下（然后参照了一下[中文文档指北](https://github.com/sparanoid/chinese-copywriting-guidelines)，不过没有详细检查规范）。
> [musicpy-QuickStart.zip](https://github.com/Rainbow-Dreamer/musicpy/files/5055874/musicpy-QuickStart.zip)
> （Github不支持Markdown文件上传，只能先打包了w）

非常感谢整理，主要是我平时忙着写musicpy的内容本身，而没有很多时间来整理Readme，当时是想把基本语法先讲一下所以写到了Readme这个一进来就看得到的地方。我之后会把这些整理到Wiki的，感谢您的支持~

**Comment by LamGC** [comment]
> > 尝试将 Readme 按照Markdown的语法整理了一下（然后参照了一下[中文文档指北](https://github.com/sparanoid/chinese-copywriting-guidelines)，不过没有详细检查规范）。
> > [musicpy-QuickStart.zip](https://github.com/Rainbow-Dreamer/musicpy/files/5055874/musicpy-QuickStart.zip)
> > （Github不支持Markdown文件上传，只能先打包了w）
> 
> 非常感谢整理，主要是我平时忙着写musicpy的内容本身，而没有很多时间来整理Readme，当时是想把基本语法先讲一下所以写到了Readme这个一进来就看得到的地方。我之后会把这些整理到Wiki的，感谢您的支持~

您也幸苦了~
（Issue由您决定关闭吧）

**Comment by Rainbow-Dreamer** [comment]
> > > 尝试将 Readme 按照Markdown的语法整理了一下（然后参照了一下[中文文档指北](https://github.com/sparanoid/chinese-copywriting-guidelines)，不过没有详细检查规范）。
> > > [musicpy-QuickStart.zip](https://github.com/Rainbow-Dreamer/musicpy/files/5055874/musicpy-QuickStart.zip)
> > > （Github不支持Markdown文件上传，只能先打包了w）
> > 
> > 
> > 非常感谢整理，主要是我平时忙着写musicpy的内容本身，而没有很多时间来整理Readme，当时是想把基本语法先讲一下所以写到了Readme这个一进来就看得到的地方。我之后会把这些整理到Wiki的，感谢您的支持~
> 
> 您也幸苦了~
> （Issue由您决定关闭吧）

好的，感谢建议了
