### ISSUE TITLE
单个音符滑音

### ISSUE THREAD

**Issue by donmor** [Rainbow-Dreamer/musicpy#22]
刚刚看到21年加入了区段pitch bend，可以使某点后的音符细微变调，这功能很赞
那么，怎么才能在某一个音符内部实现一个线性或者特定数学函数控制的pitch？比如一个长音，以B4开始，到一半时长开始降调，一直到结束时的A4，或者一个D4，开始时快速向D#4抖动一下再拉回来，配合拨弦音色整出颤音——话说MIDI支持这种指令吗？

**Comment by Rainbow-Dreamer** [comment]
musicpy里的pitch_bend类型是可以设定精确的开始时间的，单位为小节，可以是任意的整数，小数或者分数，以第1小节作为开始。  
你只需要计算想要开始的那个音符所在的小节数A和结束的小节数B，开始的小节数可以把这个音符的index之前的interval全部加起来再加1得到，结束的小节数只需要再加上这个音符的duration即可。你可以设定pitch_bend的开始时间为A到B之间的某个时间，然后到B的时候再恢复正常，这需要至少2个弯音信息，因为midi的每个弯音信息只能控制一次音调变化。  
如果当前有多个弯音信息，那么可以先写好旋律之后，把弯音信息先放在一个列表里，然后使用和弦类型自带的append函数用一个for循环逐个添加，有开始时间的弯音信息的位置可以随便放。可以把这个写成一个函数，对某一个index的音符添加推弦效果。  
如果是数学函数的话，也是可以做到的，你可以写一个函数，可以通过数输入的学函数生成一段时间范围内的弯音信息列表，然后还是用append添加就行了。  
这里必须注意的是，midi的弯音信息最大值默认只有高或低2个半音，而且不包括2个半音本身，因此如果你想变化2个半音，你可以写1.99之类的，mode设为semitones，不过这个只是默认的最大值，不同的合成器可以支持的最大的半音变化范围可能不同，有的合成器是支持超过有高或低2个半音的变化的。  
然后还需要注意一点的是，midi的弯音信息是对于一整个midi channel起作用的，也就是说某个midi通道上的某个片段如果有弯音信息，那么那个片段里这个midi通道演奏的所有音符都会跟着变化音调，所以我建议如果添加弯音信息的音符同时有其他的你不想变化音调的音符，可以放到一个新的midi通道上。  
这里是一段我现在写的硬摇滚电吉他推弦效果的musicpy代码，你可以参考一下:
```python
from musicpy import *
guitar_solo = chord('D4[.8;.], E4[.8;.], F4[.8;.], G#4[.8;.], C5[.4;.], F5[.4;.], F5[.8;.], D5[.4;.]')
bends = [
pitch_bend(1, mode='semitones', start_time=1.4375),
pitch_bend(0, mode='semitones', start_time=1.5),
pitch_bend(1.99, mode='semitones', start_time=1.77),
pitch_bend(0, mode='semitones', start_time=2)
]
for i in bends: guitar_solo.append(i)
play(guitar_solo, 120, i=30)
```
