### ISSUE TITLE
作者大大，请问有没有除取样机以外的方式导出音频？

### ISSUE THREAD

**Issue by GYPgalaxy** [Rainbow-Dreamer/musicpy#23]
您好，我现在做出peace片段后想要导出mp3或者midi格式的文件，但是配置取样机似乎较为麻烦，因为我的项目需要迁移给另外一个人，想问一下您有没有其他方式进行音频的导出？感谢您的解答！

**Comment by GYPgalaxy** [comment]
经过查看作者大大的一部分代码后我发现，直接使用musicpy.write()这个函数可以对编写的音乐进行midi格式的输出，这已经可以满足一些文件播放需求。
对于作者大大提到的取样机的设置，我这边还没有调试成功，因为我的机器是64位的python。
如果说对于导出文件的格式有需求的话可能需要寻找其他的脚本文件对Midi格式进行一个转码，这个在网上也是可查的。

**Comment by Rainbow-Dreamer** [comment]
> 经过查看作者大大的一部分代码后我发现，直接使用musicpy.write()这个函数可以对编写的音乐进行midi格式的输出，这已经可以满足一些文件播放需求。
> 对于作者大大提到的取样机的设置，我这边还没有调试成功，因为我的机器是64位的python。
> 如果说对于导出文件的格式有需求的话可能需要寻找其他的脚本文件对Midi格式进行一个转码，这个在网上也是可查的。

你好，musicpy确实有提供直接把乐理类型输出为midi文件的功能，也是基础功能之一，这个功能在[wiki](https://github.com/Rainbow-Dreamer/musicpy/wiki/Basic-syntax-of-musicpy-Part-1-%E5%9F%BA%E6%9C%AC%E8%AF%AD%E6%B3%95%EF%BC%88%E4%B8%80%EF%BC%89#%E6%92%AD%E6%94%BE%E4%B8%80%E4%B8%AA%E5%92%8C%E5%BC%A6%E4%B8%80%E4%B8%AA%E9%9F%B3%E7%AC%A6%E6%88%96%E8%80%85%E4%BB%BB%E6%84%8F%E4%B8%80%E6%AE%B5musicpy%E8%AF%AD%E8%A8%80%E4%BB%A3%E7%A0%81)里面也有具体说明。但是如果是想要输出mp3, wav, ogg这样的音频文件，就需要经过取样机模块加载采样音源导出了。64位的python也是可以使用取样机模块的，只是你需要做wiki里面写的注意1的事情，然后就可以使用了，使用未经我的修改的simpleaudio模块不会对取样机的基本功能造成影响。
