### ISSUE TITLE
Cannot hear any sound from sample code

### ISSUE THREAD

**Issue by gildurao** [Rainbow-Dreamer/musicpy#25]
Hello again,

Similar to https://github.com/Rainbow-Dreamer/sf2_loader/issues/1, I cannot hear any sound when using the sample code found in the README:

```python
from musicpy import *

guitar = (C('CM7', 4, 1/4, 1/8) ^ 2 | C('G7sus', 3, 1/4, 1/8) ^ 2
          | C('A7sus', 3, 1/4, 1/8) ^ 2 | C('Em7', 3, 1/4, 1/8) ^ 2 |
          C('FM7', 3, 1/4, 1/8) ^ 2 | C('CM7', 4, 1/4, 1/8)@1 |
          C('AbM7', 3, 1/4, 1/8) ^ 2 | C('G7sus', 3, 1/4, 1/8) ^ 2)
play((guitar * 2)-octave, 100, instrument=25)
```

**Comment by Rainbow-Dreamer** [comment]
I tried this now on my computer, windows 10, python 3.7.9 and it should plays some midi guitar sounds of a chord progression. And since switching to my ffmpeg version still did not solve the issue, I think it might be the problem of your audio driver. You can take a look at your audio driver settings.

**Comment by Rainbow-Dreamer** [comment]
This play function uses pygame.midi module to play the midi file generated once the play function is running, you should see a `temp.mid` file generated in the same path as your script, you can open it and listen if it is correct.

**Comment by gildurao** [comment]
Do not see any file generated, I will take a look at audio driver settings.

**Comment by Rainbow-Dreamer** [comment]
That might be your current file path is at the musicpy package in python path, so the midi file is generated there. You can use `os.chdir(path_to_your_current_script)` before the play function.

**Comment by Rainbow-Dreamer** [comment]
Just a check, could you use pygame to play any audio files on you computer? You can put an mp3 file on your current script's path, and try to run this part of code:
```python
from musicpy import *
pygame.mixer.music.load(name_of_file)
pygame.mixer.music.play()
```
(name_of_file should include extension .mp3)
If you cannot hear any sounds, then it is sure that your audio driver has some problems.

**Comment by gildurao** [comment]
Yeah, I cannot hear anything. I do have a Focusrite Audio interface and audio works well, but apparently Python doesn't like it. I will investigate it. Thanks for your help

**Comment by Rainbow-Dreamer** [comment]
You're welcome :)
