### ISSUE TITLE
以五线谱形式显示对象

### ISSUE THREAD

**Issue by oxygen-dioxide** [Rainbow-Dreamer/musicpy#27]
作为一个面向音乐人的工具，用五线谱显示比用文本显示更直观。

---

对于这个功能，我正在开发music21py库，用来在music21和musicpy两个库的对应数据结构之间进行转换。可以先转为music21对象，再用show()显示五线谱。

例如 https://github.com/oxygen-dioxide/music21py#%E7%A4%BA%E4%BE%8B

**Comment by Rainbow-Dreamer** [comment]
感谢提议，是有计划在musicpy中加入以五线谱的形式显示乐理结构的，这几个月可能会加入这个功能。关于你写的转换程序，我觉得目前是一种暂时的解决方法，感谢你的支持！

**Comment by oxygen-dioxide** [comment]
另外，这个库是AGPL，可能阻止了一些开发者使用这个库，如果改成稍微宽松一点的，例如LGPL，会不会好推广一些？

**Comment by Rainbow-Dreamer** [comment]
确实是应该换一个比较宽松的协议，现在这个项目还是很需要提高热度的。我觉得换成MIT是不是也不错？只是好像比LGPL还更宽松一些

**Comment by oxygen-dioxide** [comment]
换协议需要小心考虑，因为①从严格协议换到宽松协议，需要所有贡献过代码的人全部同意。②从宽松协议换到严格协议，只有新版本是严格协议，别人可以在旧版本上fork出来继续开发。
简单来说，MIT是随便用，用户可以整合到自己的程序里面，可以改，甚至可以贴上自己的牌子拿出去卖（只要ta卖得出）
LGPL可以调用，可以整合到自己的程序里面，但是库本身不能改，改了就要LGPL开源
GPL可以自己调用，可以拿来开网站，但是不能整合到自己的程序里面，否则整个程序就要GPL开源
AGPL连开网站都要按AGPL开源
---
其实如果开一个新项目，只要不是“非常牛逼”的代码，我一般就用MIT，因为我写的代码远远没有想象中那么有价值

**Comment by Rainbow-Dreamer** [comment]
明白了，感谢指点 :)
