### ISSUE TITLE
控制播放

### ISSUE THREAD

**Issue by oxygen-dioxide** [Rainbow-Dreamer/musicpy#28]
当开始播放一段旋律之后，就不能暂停播放，只能等待播放完毕，也不能拖动进度条。

---

在jupyter notebook中的解决方案：先判断是否为jupyter notebook
```py
def is_jupyter_notebook()->bool:
    try:
        get_ipython().__class__.__name__
        #jupyter notebook
        return True
    except NameError:
        #普通命令行
        return False
```

如果不是，则仍使用原来的音频api播放

如果是，则使用jupyter的api播放

播放音频：
```py
#音频数据为audiodata，numpy数组
if(is_jupyter_notebook()):
    from IPython.display import Audio
    return Audio(data=audiodata, rate=44100)
```
效果：
![image](https://user-images.githubusercontent.com/54425948/134754687-e4316b6d-75b6-43dc-ae13-639f5512cd90.png)

**Comment by Rainbow-Dreamer** [comment]
控制播放目前是不行的，因为musicpy的play函数的设计机制是把乐理结构写入一个MIDI文件，然后使用pygame的mixer模块播放这个MIDI文件。pygame目前是不支持MIDI文件的暂停和播放位置的设定的，因此如果在本地离线运行，那么使用播放器软件打开生成的MIDI文件进行播放可能是最好的办法。生成的MIDI文件如果没有指定文件路径，就会生成在当前运行的script的文件路径下，文件名默认为`temp.mid`。
