### ISSUE TITLE
关于track类型与build函数的几个问题（可能是bug）

### ISSUE THREAD

**Issue by oxygen-dioxide** [Rainbow-Dreamer/musicpy#29]
1. 用build函数创建piece，传入track时，只有当所有的track都有名称track_name时，输出piece的音轨才有名称。如果输入的某个track没有名称，则其他音轨的名称在piece中丢失
![image](https://user-images.githubusercontent.com/54425948/134789774-b5672c2f-a316-4d2e-bf0f-ef24099081b7.png)
查看了代码，发现是写死在代码里面的。
https://github.com/Rainbow-Dreamer/musicpy/blob/ead467d168569d2cc4fd1191d788370118a5694c/musicpy/musicpy.py#L3019-L3020
是故意这样设计的吗？
2. build不支持将数量不确定的track构建为一个piece。例如，这些track不是由用户在代码中写入的，而是由其他文件转换过来的，存放在一个list中,只能用append一个一个加。（这个设计不是很pythonic，像numpy这样的库会要求用户将所有的track先装入一个list，再传入函数，例如`build([track1,track2,track3])`，而不是`build(track1,track2,track3)`）
3. build不支持track与列表形式混输

**Comment by Rainbow-Dreamer** [comment]
1. 目前是故意这样设计的，传入的音轨的属性中，只有当所有的音轨都有这一属性的时候才会给生成的乐曲类型赋予这一属性。这个我可以改进一下，改成只有当所有的音轨都没有这一属性才不进行赋值。
2. 其实这种情况可以使用python的可迭代对象拆包语法，比如`build(*[track1,track2,track3])`，就可以解决问题。不过我可以对这个函数增加音轨的列表的读取的功能。
3. 这个也可以增加支持。
感谢你的反馈和改进意见 :) 下个版本中这些功能都可以实现

**Comment by oxygen-dioxide** [comment]
> 2. 其实这种情况可以使用python的可迭代对象拆包语法，比如`build(*[track1,track2,track3])`，就可以解决问题。不过我可以对这个函数增加音轨的列表的读取的功能。
那还是别添加支持了，把可迭代对象拆包语法写进文档就行。做一件事情的方法太多的话代码不好维护。

**Comment by Rainbow-Dreamer** [comment]
我认为构建乐曲类型还是应该添加对于可迭代对象的原生支持的，一直用拆包也不是很好看XD
目前的改进中，我已经把传入列表的所有参数个数必须相同的限制去掉了，如果参数个数不同，会进行默认值补余。音轨类型和列表的混输也已经实现，不过暂时还在测试中，等全部case通过了就更新版本。

> > 1. 其实这种情况可以使用python的可迭代对象拆包语法，比如`build(*[track1,track2,track3])`，就可以解决问题。不过我可以对这个函数增加音轨的列表的读取的功能。
> 
> 那还是别添加支持了，把可迭代对象拆包语法写进文档就行。做一件事情的方法太多的话，用户写调用这个库的代码不好维护。

我认为构建乐曲类型还是应该添加对于可迭代对象的原生支持的，一直用拆包也不是很好看XD
目前的改进中，我已经把传入列表的所有参数个数必须相同的限制去掉了，如果参数个数不同，会进行默认值补余。音轨类型和列表的混输也已经实现，不过暂时还在测试中，等全部case通过了就更新版本。

**Comment by Rainbow-Dreamer** [comment]
> > 1. 其实这种情况可以使用python的可迭代对象拆包语法，比如`build(*[track1,track2,track3])`，就可以解决问题。不过我可以对这个函数增加音轨的列表的读取的功能。
> 
> 那还是别添加支持了，把可迭代对象拆包语法写进文档就行。做一件事情的方法太多的话，用户写调用这个库的代码不好维护。

我认为构建乐曲类型还是应该添加对于可迭代对象的原生支持的，一直用拆包也不是很好看XD
目前的改进中，我已经把传入列表的所有参数个数必须相同的限制去掉了，如果参数个数不同，会进行默认值补余。音轨类型和列表的混输也已经实现，不过暂时还在测试中，等全部case通过了就更新版本。

**Comment by Rainbow-Dreamer** [comment]
已更新版本，wiki会跟着更新，感谢你为这个项目做出的改进 :)
