### ISSUE TITLE
play 时，sh: temp.mid: command not found 报错

### ISSUE THREAD

**Issue by rovesoul** [Rainbow-Dreamer/musicpy#3]
作者您好，我按照b站教程，运行如下代码
```python
from musicpy import *

a=note('A',5,duration=3)
b=chd("C5","maj7",duration=1,intervals=1)
play(a)
# print(b)
```
play这句报错：**sh: temp.mid: command not found**

请问我该如何处理.

我看了一下play函数的源代码如下
```python
def play(chord1,
         tempo=80,
         track=0,
         channel=0,
         time1=0,
         track_num=1,
         name='temp.mid',
         modes='quick',
         instrument=None,
         save_as_file=True):
    file = write(name_of_midi=name,
                 chord1=chord1,
                 tempo=tempo,
                 track=track,
                 channel=channel,
                 time1=time1,
                 track_num=track_num,
                 mode=modes,
                 instrument=instrument,
                 save_as_file=save_as_file)
    if save_as_file:
        result_file = name
        if sys.platform.startswith('win'):
            os.startfile(result_file)
        elif sys.platform.startswith('linux'):
            import subprocess
            subprocess.Popen(result_file)
        elif sys.platform == 'darwin':
            os.system(result_file)
    else:
        return file
```
我的电脑是mac，该如何处理这个问题呢。现在在同级目录下有temp.mid这个文件，只是不能播放。需要拖入第三方录音软件听。

**Comment by Rainbow-Dreamer** [comment]
你好，play这个函数我特意有写跨系统平台支持的，在"if save_as_file:"那一块就是分windows, mac, linux三个系统的情况来分别写对应的播放生成midi文件的代码，对应的都是启用电脑里的播放器软件来播放midi文件。由于本人身边没有mac，所以mac对应的启动代码主要是参考网上stackoverflow里面某位仁兄写的mac系统os模块播放文件的代码，没法进行测试，有可能这句“elif sys.platform == 'darwin': os.system(result_file)”是有问题的。我会去看看如何修复这个问题的，可能换一个跨平台支持更好的播放音乐文件的模块，在此之前暂时先拖进播放器听吧，很抱歉。

**Comment by Rainbow-Dreamer** [comment]
你好，刚才去研究了下mac系统的terminal播放音乐文件的指令，现在已经对原来的play函数的mac系统部分的代码做出了修改，并且github和pypi都更新了，现在应该是可以顺利播放了，请重新卸载musicpy再安装一下（pip install musicpy会自动安装最新版本），如果还有遇到问题请及时跟我说，谢谢。

**Comment by Rainbow-Dreamer** [comment]
> 作者您好，我按照b站教程，运行如下代码
> 
> ```python
> from musicpy import *
> 
> a=note('A',5,duration=3)
> b=chd("C5","maj7",duration=1,intervals=1)
> play(a)
> # print(b)
> ```
> 
> play这句报错：**sh: temp.mid: command not found**
> 
> 请问我该如何处理.
> 
> 我看了一下play函数的源代码如下
> 
> ```python
> def play(chord1,
>          tempo=80,
>          track=0,
>          channel=0,
>          time1=0,
>          track_num=1,
>          name='temp.mid',
>          modes='quick',
>          instrument=None,
>          save_as_file=True):
>     file = write(name_of_midi=name,
>                  chord1=chord1,
>                  tempo=tempo,
>                  track=track,
>                  channel=channel,
>                  time1=time1,
>                  track_num=track_num,
>                  mode=modes,
>                  instrument=instrument,
>                  save_as_file=save_as_file)
>     if save_as_file:
>         result_file = name
>         if sys.platform.startswith('win'):
>             os.startfile(result_file)
>         elif sys.platform.startswith('linux'):
>             import subprocess
>             subprocess.Popen(result_file)
>         elif sys.platform == 'darwin':
>             os.system(result_file)
>     else:
>         return file
> ```
> 
> 我的电脑是mac，该如何处理这个问题呢。现在在同级目录下有temp.mid这个文件，只是不能播放。需要拖入第三方录音软件听。

你好，刚才去研究了下mac系统的terminal播放音乐文件的指令，现在已经对原来的play函数的mac系统部分的代码做出了修改，并且github和pypi都更新了，现在应该是可以顺利播放了，请重新卸载musicpy再安装一下（pip install musicpy会自动安装最新版本），如果还有遇到问题请及时跟我说，谢谢。

**Comment by Rainbow-Dreamer** [comment]
> 作者您好，我按照b站教程，运行如下代码
> 
> ```python
> from musicpy import *
> 
> a=note('A',5,duration=3)
> b=chd("C5","maj7",duration=1,intervals=1)
> play(a)
> # print(b)
> ```
> 
> play这句报错：**sh: temp.mid: command not found**
> 
> 请问我该如何处理.
> 
> 我看了一下play函数的源代码如下
> 
> ```python
> def play(chord1,
>          tempo=80,
>          track=0,
>          channel=0,
>          time1=0,
>          track_num=1,
>          name='temp.mid',
>          modes='quick',
>          instrument=None,
>          save_as_file=True):
>     file = write(name_of_midi=name,
>                  chord1=chord1,
>                  tempo=tempo,
>                  track=track,
>                  channel=channel,
>                  time1=time1,
>                  track_num=track_num,
>                  mode=modes,
>                  instrument=instrument,
>                  save_as_file=save_as_file)
>     if save_as_file:
>         result_file = name
>         if sys.platform.startswith('win'):
>             os.startfile(result_file)
>         elif sys.platform.startswith('linux'):
>             import subprocess
>             subprocess.Popen(result_file)
>         elif sys.platform == 'darwin':
>             os.system(result_file)
>     else:
>         return file
> ```
> 
> 我的电脑是mac，该如何处理这个问题呢。现在在同级目录下有temp.mid这个文件，只是不能播放。需要拖入第三方录音软件听。

你好，刚才去研究了下mac系统的terminal播放音乐文件的指令，现在已经对原来的play函数的mac系统部分的代码做出了修改，并且github和pypi都更新了，现在应该是可以顺利播放了，请卸载musicpy再重新安装一下（pip install musicpy会自动安装最新版本），如果还有遇到问题请及时跟我说，谢谢。
