### ISSUE TITLE
'str' object has no attribute 'track_number'

### ISSUE THREAD

**Issue by aliushn** [Rainbow-Dreamer/musicpy#34]
musicpy\musicpy.py", line 771, in write
    current_chord.track_number, current_chord.start_times, current_chord.instruments_numbers, current_chord.bpm, current_chord.tracks, current_chord.track_names, current_chord.channels, current_chord.pan, current_chord.volume
AttributeError: 'str' object has no attribute 'track_number'

**Comment by Rainbow-Dreamer** [comment]
你好，可以把产生这个报错信息的代码发一下么

**Comment by Rainbow-Dreamer** [comment]
你好，请看wiki里write函数的使用说明，只能播放乐理类型或者和弦类型的列表，字符串是不行的。
