### ISSUE TITLE
Can you provide a basic example of how to use the sampler

### ISSUE THREAD

**Issue by dustyny** [Rainbow-Dreamer/musicpy#35]
I'm trying to get started with the sampler. I'm finding it hard to get started, the information is here but it's a bit to complicated for someone who doesn't know this module. It would help if there was a very simple example. Ive spent the last couple of days trying to figure out how to start. 
 
 If I had an example that shows how to do the following, it would be much easier to start.

 1 drum loaded as a WAV file with a very simple sequence.  
 I sf2 loaded with an explanation of how to load a specific preset 
simple chord progression of the sF2 
 A short loop made from the 2 sequences. 
 Play the loop
 Export the loop

🙏🏼🙏🏼

**Comment by dustyny** [comment]
I got the basics working using the code below. My "drum" folder has 2 wav files, bass drum (C2.wav) & snare drum (E2.wav). 

current_sampler = sampler(1)
current_sampler.load(0, './drum/')
current_sampler.modules(0)
part1 = drum('0[1],0[1],2[1],2').notes
result = P([part1], sampler_channels=[0])
current_sampler.play(part1, bpm=40)

**Comment by Rainbow-Dreamer** [comment]
For sampler examples, I wrote a whole chapter of sampler examples in wiki, you can click [here](https://github.com/Rainbow-Dreamer/musicpy/wiki/musicpy-sampler-module-composition-code-examples)
Maybe these examples are too complicated to follow (even if you learn the basic syntax of musicpy and sampler module), I will provide a step-to-step simple sampler example in this chapter later, with comments on every step.
Thanks for the feedback.
