### ISSUE TITLE
Can't load the module if there is no audio interface

### ISSUE THREAD

**Issue by dustyny** [Rainbow-Dreamer/musicpy#36]
I'd like to use this module to generate loops using a server. But when you try to load the module it tries to initiate the audio interface which fails without an audio interface. 

I don't need to playback the audio, I just need to export the loops I generate as WAV file.  

The work around is to create a dummy audio interface but it's complicated and I'm having issues keeping the dummy interface running.

**Comment by Rainbow-Dreamer** [comment]
Thanks for the feedback. Yes, currently the initialization of musicpy and its sampler module requires audio interface to start with, which means it cannot run on a server without audio interface. Could you show me the code and error producing by loading the module please? I will try to add functionality to initialize without audio interface later.

**Comment by Rainbow-Dreamer** [comment]
Thanks for the feedback. Yes, currently the initialization of musicpy and its sampler module requires audio interface to start with, which means it cannot run on a server without audio interface. I improve the initialization of musicpy, and it now does not requires any audio interface to start with, you can now generate wav files using this module on a server.
