### ISSUE TITLE
Sampler doesn't properly handle 32bit wav files

### ISSUE THREAD

**Issue by dustyny** [Rainbow-Dreamer/musicpy#37]
When playing wav samples of 32bit/44.1khz wav files, the sampler plays them back at the wrong speed which pitches them down. I haven't checked but I would guess that 8/12bit files will playback pitched up.

**Comment by Rainbow-Dreamer** [comment]
Could you show me the code produce this issue please?

**Comment by Rainbow-Dreamer** [comment]
Thanks for the feedback, this is actually a pydub's issue, as it cannot handle wav files that is not 16 bit properly, which is a common issue being mentioned a lot in pydub's issues section, a solution I find is to add `sound.set_sample_width(2)` to reset the wav samples into 16 bit when the sample width that pydub gets from the wav file is not 2 (according to pydub's documentation, sample width 1 means 8 bit, 2 means 16 bit, etc.), and it will work fine.
