### ISSUE TITLE
Note example

### ISSUE THREAD

**Issue by mastephe** [Rainbow-Dreamer/musicpy#38]
Could you give a simple example on your Wiki how to create a simple melody.  It is not clear to me how to play a simple sequence of notes.  I tried the only_notes function but get the same output.  If I want to play notes without the cords how would you do this?

**Comment by Rainbow-Dreamer** [comment]
In musicpy, a melody and a chord are all treated as a combination of notes, which is the design of the chord type in musicpy, so you can create chords and melodies all using the chord type. You can read the data structures section in wiki for more details. The `only_notes` function is for clearing the non-note types in a chord type such as tempo type and pitch bend type.
If you want to play a sequence of notes, you can build up a chord type which contains these notes, and then use `play` function to play it. For example, here is a simple sequence of notes that represents a melody:
```python
melody = chord('C5, C5, G5, G5, A5, A5, G5, F5, F5, E5, E5, D5, D5, C5',
                           duration=[1/8, 1/8, 1/8, 1/8, 1/8, 1/8, 1/4, 1/8, 1/8, 1/8, 1/8, 1/8, 1/8, 1/4],
                           interval=[1/8, 1/8, 1/8, 1/8, 1/8, 1/8, 1/4, 1/8, 1/8, 1/8, 1/8, 1/8, 1/8, 1/4])
```
You can play this melody, for example, at 80 BPM
```python
play(melody, bpm=80)
```
There are many other syntax to create a chord type (which is a combination of notes) in musicpy, you can refer to wiki.
I hope this helps.
