### ISSUE TITLE
Can someone compare this project to SonicPi?

### ISSUE THREAD

**Issue by abbychau** [Rainbow-Dreamer/musicpy#4]

**Comment by Rainbow-Dreamer** [comment]
你好，sonic pi这个项目我在今年3月份才从油管有人做的介绍视频发现，（我这个项目是去年10月开始做的，那时候不知道有sonic pi的存在），sonic pi也可以让你写代码来作曲，但是运作逻辑以及设计思路还有想实现的事情跟我这个完全不一样。sonic pi是主打现场代码作曲，通过代码调用音源，设定ADSR还有其他的声音参数加上输入音符与和弦名称来得到想要的音。我这个是后台代码作曲，生成midi文件，而且在乐理上面可以做的事情比sonic pi要复杂并且全面非常多，举例：比如可以通过很简单的语法计算和弦的某个转位，voicings，把和弦进行拼接，倒序，重复指定的次数；可以构建一个音阶，按照级数调用和弦，计算某个和弦关于这个音阶的负面和声，计算某个级数的副属和弦等等。musicpy有自己的独立的一套作曲语言的语法结构，这些我在这个项目的wiki里面有分章节详细的描述，和sonic pi的语法逻辑与数据结构设计都完全不同。我最开始开发musicpy的初衷是把整个乐理体系用数理逻辑高度抽象化，然后可以用数学形式的语言来表达乐理逻辑。我致力于在musicpy这个项目中将整个乐理体系彻底地数学模型化，计算机化，构建一整个计算机能够理解的乐理系统，让大家可以在musicpy这个世界里研究任何跟音乐，乐理相关的算法，智能分析，实验性作曲等等。建立在musicpy的数据结构基础上，我也开发出了分离主旋律和和弦走向的算法（目前已经开发出来一个效果很好的），判断一首曲子的调性的算法，以及对曲子进行和声分析的乐理算法，判断复杂和弦的构造的算法等等（这些算法都在musicpy里面）。所以最主要的就是想做一个专业乐理的高度抽象研究性语言，可以用于复杂的乐理逻辑作曲与乐理分析和研究，也就是说musicpy更加偏向乐理学术方面，和sonic pi所做的事情与方向都完全不同。musicpy的音符类，和弦类，音阶类每一个类都有很丰富的乐理逻辑设计。如果想了解musicpy的具体的语法与数据结构设计还有乐理分析算法的实践，请看这个项目的wiki，https://github.com/Rainbow-Dreamer/musicpy/wiki

**Comment by abbychau** [comment]
謝謝答疑
