### ISSUE TITLE
请教大佬如何在一个chord的起始位置添加休止符？

### ISSUE THREAD

**Issue by JinYuan0209** [Rainbow-Dreamer/musicpy#41]
`lambda x: (rest(1/4) | x @ [-2.2, -2.3, -2.3] % ([1/4, 1/4, 1/4], [1/4, 1/4, 1/4]))`
TypeError: unsupported operand type(s) for |: 'rest' and 'chord'

**Comment by Rainbow-Dreamer** [comment]
目前可以设置chord的开始时间`start_time`，单位为小节，左加间隔的语法我之后新的版本会补上的，感谢反馈

**Comment by Rainbow-Dreamer** [comment]
现在的最新版本中可以直接左加休止符了

**Comment by JinYuan0209** [comment]
@Rainbow-Dreamer thanks a lot.
