### ISSUE TITLE
split_melody返回的note对象

### ISSUE THREAD

**Issue by hsuxiang** [Rainbow-Dreamer/musicpy#44]
你好，请问我在用.split_melody(mode='notes')函数分离得到的主旋律音符对象，我的note对象里的duration是float类型的，这个是秒为单位的还是wiki文档里写的以节为单位的呢？如果是以节为单位的，是以默认的480ticks_per_beat和4/4分音符计算的，还是按每首歌自己不同的情况计算的
![Uploading image.png…]()

**Comment by hsuxiang** [comment]
![image](https://user-images.githubusercontent.com/77951517/202889743-8cbb5735-c34c-4c52-b865-8caee4654480.png)

**Comment by Rainbow-Dreamer** [comment]
您好，这个问题在私聊中已回答，这里先关闭了:)
