### ISSUE TITLE
Demos won't work without an explicit sleep

### ISSUE THREAD

**Issue by crystaldust** [Rainbow-Dreamer/musicpy#47]
Hi, I tried some of the demos of sf2_loader and musicpy, but without sleeping, all the notes/pieces won't be played and the program exited in advance. After looking into the code and doing some googling, I found that the audio is played underlying by pygame.mixer, which is supposed to play the audio in the background without blocking(which makes sense in game, discussed in [this stackoverflow thread](https://stackoverflow.com/questions/54600297/why-does-pygame-need-time-sleep-in-to-play-sound-before-exiting)). So after adding a sleep(some_seconds), the demos work as expected.

I tried this on Windows and Linux, with pygame version@2.0.2, `sleep` is essential in both systems.  Is there anything else I have to care if I want to try the demo without `sleep`? Or this is the design then maybe it's better to add a line of code in the tutorial demos?

Oh, almost forgot to say, it's a great project, good job!

**Comment by Rainbow-Dreamer** [comment]
Thanks for the support. This is more of a IDE-specific issue, when you use python IDE like Pycharm or VS Code, this issue will occur, since these IDE won't wait till the pygame's function that plays MIDI file ends, they will stops the whole process after all of the code are executed without waiting for the playback of the MIDI file. You won't encounter this issue with more interactive python IDE, such as Jupyter Notebook, Wing IDE, or directly use the interactive shell of python in terminal. This issue is actually already mentioned in the frequently asked question section in wiki, and there is a built-in solution to it, you can check it [here](https://github.com/Rainbow-Dreamer/musicpy/wiki/Frequently-Asked-Questions).

**Comment by crystaldust** [comment]
Thanks, get the point. The REPL environments would always wait for all tasks in foreground/background finished to recover the session. I guess it would be much nicer to tell user this or give a link to FAQ in the documents(I guess most programmers use IDEs rather than a REPL environment :) ). I spent almost a whole day to debug it, misled by the warning messages in Linux saying ALSA unable to open slave, cannot connect to JACK server blablabla, also by myself suspecting I didn't specify the correct output device(my bad, pygame will select the currently active device).

BTW I found the `play_piece` sample code doesn't work in [sf2_loader's document](https://github.com/Rainbow-Dreamer/sf2_loader#Play-notes-chords-pieces-and-MIDI-files). Guess it's a missing ref to musicpy module's `chord` function? Like the diff [here](https://github.com/Rainbow-Dreamer/sf2_loader/compare/main...crystaldust:sf2_loader:main#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5L563)?

**Comment by Rainbow-Dreamer** [comment]
Thanks for the advice, I will add a reminder about this in musicpy and sf2_loader's README.
For the `play_piece` sample code, yes it is a typo missing a `chord` function ref, I will correct this soon.

**Comment by crystaldust** [comment]
Aha, I see. `C` is alias of `trans` in the code. Then I strongly suggest show the document reader a `real piece` with tempo but not just a chord(playing at the same time):
```python3
import sf2_loader as sf
loader = sf.sf2_loader('SOME_SOUND_FONT_FILE.sf2')

# Here we have a chord marching from C -> F
current_piece = sf.mp.P(
    [
        # C is to translate human-readable chord name to notes
        sf.mp.C('Cmaj7') % (1, 1 / 8) * 4,
        sf.mp.C('Fmaj7') % (1, 1 / 8) * 4,

        # The code below does exactly the same job
        # sf.mp.chord('C, E, G, B') % (1, 1 / 8) * 4,
        # sf.mp.chord('F, A, C, E') % (1, 1 / 8) * 4
    ],
    start_times=[0, 2],
    bpm=150)
loader.play_piece(current_piece)

# Need just in an IDE
from time import sleep
sleep(6.5)
```

Then a link to the [wiki about the piece](https://github.com/Rainbow-Dreamer/musicpy/wiki/Basic-syntax-of-piece-type) would be great!

**Comment by Rainbow-Dreamer** [comment]
That's a good suggestion, I will make a change to the document soon. I also add a `wait` pararmeter to all play functions of sf2_loader now, which is the same usage as musicpy, and I will update README about this too. Thanks for the suggestion!

**Comment by crystaldust** [comment]
Yea, I tried the latest code with `wait` param, works perfectly, thanks for the great job!

**Comment by Rainbow-Dreamer** [comment]
You're welcome :)
