### ISSUE TITLE
翻譯和弦判斷算法github wiki的文檔 

### ISSUE THREAD

**Issue by Kuo-TingKai** [Rainbow-Dreamer/musicpy#48]
您好，
我對於和弦判斷算法邏輯這部分特別有興趣，我想要幫忙將這部分算法條目給英翻中。
但我對於github wiki的使用不夠熟，想請問有沒有甚麼特別的內嵌功能可以在原來英文條目添加中文內容，做language switching的時候只顯示特定語言內容；還是一定得開新的頁面添加中文條目?

**Comment by Rainbow-Dreamer** [comment]
您好，感謝支持這個項目，不過[中文版](https://github.com/Rainbow-Dreamer/musicpy/wiki/按照乐理逻辑判断任意一组音组成的和弦类型的算法)的已經有了，我在寫wiki的時候都是英文和中文同時更新的。
關於github wiki的語言切換，因為是直接支持markdown語法的，所以可以英文和中文寫在一個頁面中，分別用自帶語言後綴的標題，然後在開頭放markdown的內部標題鏈接，就可以鼠標點擊跳轉到每個語言對應的開頭標題了。

**Comment by Kuo-TingKai** [comment]
> 您好，感謝支持這個項目，不過[中文版](https://github.com/Rainbow-Dreamer/musicpy/wiki/%E6%8C%89%E7%85%A7%E4%B9%90%E7%90%86%E9%80%BB%E8%BE%91%E5%88%A4%E6%96%AD%E4%BB%BB%E6%84%8F%E4%B8%80%E7%BB%84%E9%9F%B3%E7%BB%84%E6%88%90%E7%9A%84%E5%92%8C%E5%BC%A6%E7%B1%BB%E5%9E%8B%E7%9A%84%E7%AE%97%E6%B3%95)的已經有了，我在寫wiki的時候都是英文和中文同時更新的。 關於github wiki的語言切換，因為是直接支持markdown語法的，所以可以英文和中文寫在一個頁面中，分別用自帶語言後綴的標題，然後在開頭放markdown的內部標題鏈接，就可以鼠標點擊跳轉到每個語言對應的開頭標題了。

謝謝即時的回覆，想請問語言後綴指的是甚麼。我本來想說fork你的repo直接參考你寫的markdown語法學習一下，但發現fork之後不包括原專案的github wiki (苦笑)

**Comment by Rainbow-Dreamer** [comment]
我的意思是指大寫的標題帶上語言後綴，比如`标题 (en)` `标题 (zh_CN)`這樣。或者可以是一樣的，但是markdown代碼需要寫-1 -2进行区分，比如说这个[repo](https://github.com/Rainbow-Dreamer/easy-sampler)的README作为例子。

**Comment by Rainbow-Dreamer** [comment]
不客氣~
