### ISSUE TITLE
能不能写几个example

### ISSUE THREAD

**Issue by ShotoZhao** [Rainbow-Dreamer/musicpy#5]
能直接运行的那种

**Comment by Rainbow-Dreamer** [comment]
在我写的wiki里面的语法章节第二部分里面有，网址https://github.com/Rainbow-Dreamer/musicpy/wiki/Basic-grammar-of-musicpy--Part-2-%E5%9F%BA%E7%A1%80%E8%AF%AD%E6%B3%95%EF%BC%88%E4%BA%8C%EF%BC%89
