### ISSUE TITLE
Friendly reminder of updating the scale page on Wiki

### ISSUE THREAD

**Issue by crystaldust** [Rainbow-Dreamer/musicpy#50]
Hi, I just found there is a small mismatch of variable assignment here:
[Construct scales according to interval relationships or key names](https://github.com/Rainbow-Dreamer/musicpy/wiki/Basic-syntax-of-scale-type#construct-scales-according-to-interval-relationships-or-key-names),

where a C5 major scale should be assigned with intervals `[2, 2, 1, 2, 2, 2, 1]`(guess it's a typo with an additional 2 in the list):
```python
scale('C5', interval = [2,2,1,2,2,2,2,1])
```
Close the issue any time when it's updated :-)

**Comment by Rainbow-Dreamer** [comment]
Thanks for the reminder, this typo is already corrected now.
