### ISSUE TITLE
Question about running code in colab enviroment and exporting as midi / wav file

### ISSUE THREAD

**Issue by timtensor** [Rainbow-Dreamer/musicpy#52]
Hi, thanks for the library . 
I have a  query 
Is it not possible to run musicpy in google collab ? I always get mix not initialized error after installing the library 
Second how can one export the chord progression as a midi file or wave file ?

**Comment by Rainbow-Dreamer** [comment]
It is possible to play midi file generated from musicpy in google colab, an easy way is to use midi player like fluidsynth to render the midi file to an audio file, and then use `IPython.display.Audio` to play the audio file.
I made a google colab notebook now to succesfully play a C major chord generated from musicpy, you can click [here](https://colab.research.google.com/drive/1FZ1oSPJWFzp0cfBCzEkPXW7eh5F7SkmE?usp=sharing) to run it and make a copy of it as a template.

**Comment by timtensor** [comment]
Thanks for the template. Just another question. I dont think the `play` command works in colab . But midi yes.

**Comment by Rainbow-Dreamer** [comment]
Yes, the `play` function works as it firstly generate a midi file and then play the midi file using pygame.mixer, which requires local audio driver, here in colab the more recommended way is to use `IPython.display.Audio` to generate a playable audio clip from the audio rendered from the midi file.

**Comment by timtensor** [comment]
thank you is the right method be like this inorder to make play work ? 
```
`w = (C('Cmadd9,add11',5) @ [1,3,1.1,4,2.1,5,2.1,4] % (1/2,1/8) * 2 |
C('A#add9,add11',4) @ [1,3,1.1,4,2.1,5,2.1,4] % (1/2,1/8) * 2 |
C('G#add9',4) @ [1,3,1.1,4,2.1,4,1.1,3] % (1/2,1/8) * 2 |
C('A#add9',4) @ [1,3,1.1,4,2.1,4,1.1,3] % (1/2,1/8) * 2)

w2 = translate('C2;C3[l:2], i:2, A#1;A#2[l:2], i:2, G#1;G#2[l:2], i:2, A#1;A#2[l:2]')

# Write the song as a MIDI file
write(w2,
      bpm=100,
      channel=0,
      name='funky_song.mid',
      save_as_file=True)`
```

**Comment by Rainbow-Dreamer** [comment]
The `play` function uses the `write` function to generate the midi file, so yes, by using `write` function, the midi file `funky_song.mid` will be generated on your current colab notebook, and then you can refer to the template, use fluidsynth to render the midi file to an audio file, and use `IPython.display.Audio` to play it.
