### ISSUE TITLE
关于让构建和弦时和弦音的显示更符合乐理的建议

### ISSUE THREAD

**Issue by usingnamespacestc** [Rainbow-Dreamer/musicpy#55]
现在使用和弦语法构成和弦似乎默认是以升号表示半音。以三和弦为例，一般认为三和弦是1 3 5的变化，比如

C 大三和弦：1 3 5
Cm 小三和弦 ：1 b3 5
Caug 增三和弦：1 3 #5
Cdim 减三和弦 ：1 b3 b5

当使用musicpy.C('Cdim')构建和弦，和弦的构成音为[C4, D#4, F#4]，能否修改为默认显示[C4, Eb4, Gb4]？这样对于后续进行乐理角度的分析更方便。其他七九十一和弦等等复杂和弦同理。

**Comment by Rainbow-Dreamer** [comment]
感谢建议，之后新版本中会加入音程类，和弦构成会采用音程构建的形式，可以严格计算出准确的升降音。
