### ISSUE TITLE
error: mixer not initialized

### ISSUE THREAD

**Issue by sugizo** [Rainbow-Dreamer/musicpy#58]
**environment** 
google colab

**code** 
same like on your git and pypi
```
pip install -U musicpy 
from musicpy import *
guitar = (C('CM7', 3, 1/4, 1/8)^2 |
          C('G7sus', 2, 1/4, 1/8)^2 |
          C('A7sus', 2, 1/4, 1/8)^2 |
          C('Em7', 2, 1/4, 1/8)^2 | 
          C('FM7', 2, 1/4, 1/8)^2 |
          C('CM7', 3, 1/4, 1/8)@1 |
          C('AbM7', 2, 1/4, 1/8)^2 |
          C('G7sus', 2, 1/4, 1/8)^2) * 2
play(guitar, bpm=100, instrument=25)
```

**result**
```
error                                     Traceback (most recent call last)
[<ipython-input-9-e2f1c6daee5e>](https://localhost:8080/#) in <cell line: 1>()
----> 1 play(guitar, bpm=100, instrument=25)

[/usr/local/lib/python3.10/dist-packages/musicpy/musicpy.py](https://localhost:8080/#) in play(current_chord, bpm, channel, start_time, name, instrument, i, save_as_file, msg, nomsg, ticks_per_beat, ignore_instrument, ignore_bpm, ignore_track_names, wait, **midi_args)
    291     if save_as_file:
    292         result_file = name
--> 293         pygame.mixer.music.load(result_file)
    294         pygame.mixer.music.play()
    295         if wait:

error: mixer not initialized
```

best regards

**Comment by Rainbow-Dreamer** [comment]
Thanks for the feedback, on google colab you need midi player like fluidsynth to render the midi file to an audio file, and then use IPython.display.Audio to play the audio file. You can click [here](https://colab.research.google.com/drive/1FZ1oSPJWFzp0cfBCzEkPXW7eh5F7SkmE?usp=sharing) to run it and make a copy of it as a template.

**Comment by sugizo** [comment]
already tested it, but compare with the mp3 file on your google drive 
the output is different :
0:01 second on colab 
and 
your mp3 file on google drive with the same code is 0:12 second

**colab code**
```
!apt update
!apt-get install -y fluidsynth
pip install musicpy
from IPython.display import Audio
from musicpy import *
guitar = (C('CM7', 3, 1/4, 1/8)^2 |
          C('G7sus', 2, 1/4, 1/8)^2 |
          C('A7sus', 2, 1/4, 1/8)^2 |
          C('Em7', 2, 1/4, 1/8)^2 | 
          C('FM7', 2, 1/4, 1/8)^2 |
          C('CM7', 3, 1/4, 1/8)@1 |
          C('AbM7', 2, 1/4, 1/8)^2 |
          C('G7sus', 2, 1/4, 1/8)^2) * 2
print(guitar)
write(q, bpm = 100, instrument = 25)
!ls -la
!fluidsynth -F temp_100_25.wav temp.mid
Audio('temp_100_25.wav', autoplay = True)
```

**ref**
https://musicpy.readthedocs.io/en/latest/Introduction/

your mp3 from the same like code above (in google colab it produce only 0:01 second in wav file
while
in your mp3 around 0:12
https://drive.google.com/file/d/104QnivVmBH395dLaUKnvEXSC5ZBDBt2E/view

best regards

**Comment by Rainbow-Dreamer** [comment]
Your colab code has a typo which causes this issue, change the line
`write(q, bpm = 100, instrument = 25)` to
`write(guitar , bpm = 100, instrument = 25)`
then you will get the correct audio.
