### ISSUE TITLE
[feature req] Integration with hookpad ? 

### ISSUE THREAD

**Issue by timtensor** [Rainbow-Dreamer/musicpy#59]
Hi , first of all kudos to work done by you . I am not sure if you are aware of hook pad theory ? basically it is sketching notes and chords with tones of options . It helps in understanding theory in a visual way. I am wondering if the sketch pad can be converted directly into a midi file with musicpy ? 

An example for one of the songs is here :https://www.hooktheory.com/theorytab/view/the-beatles/here-comes-the-sun where you can edit the chords and notes. 

I think it could be super useful to use both musicpy and hooktheory for faster learning. It was just a thought as hook theory has also lots of music resources

**Comment by Rainbow-Dreamer** [comment]
Thanks for the suggestions, this idea looks interesting, I will look into this when I have more free time from work.
