### ISSUE TITLE
也许应该增加一个用这个语言的JupterNotebook，配合H5 audio编程的前端play ground.

### ISSUE THREAD

**Issue by Teaonly** [Rainbow-Dreamer/musicpy#6]
否则，仅仅只是代码和逻辑化乐理，无法抓住人的注意力，至少不能马上看到Demo

**Comment by Rainbow-Dreamer** [comment]
你好，如果你有看我在这个项目写的wiki的话，在“如何使用musicpy”那一章节，我有介绍我专门为musicpy这门音乐编程语言专门设计的编辑器，可以直接输入代码然后自动运行，也有自动补全功能，还有一些内置的语法糖（比如在一行音乐代码前加上/就可以直接播放），这个编辑器的文件是musicpy editor.pyw，就在musicpy的代码文件夹里，打开前请先看read me first!.txt这个文件。wiki的介绍这个编辑器的章节的地址https://github.com/Rainbow-Dreamer/musicpy/wiki/How-to-use-musicpy-%E5%A6%82%E4%BD%95%E4%BD%BF%E7%94%A8musicpy

**Comment by Rainbow-Dreamer** [comment]
你好，如果你有看我在这个项目写的wiki的话，在“如何使用musicpy”那一章节，我有介绍我专门为musicpy这门音乐编程语言设计的编辑器，可以直接输入代码然后自动运行，也有自动补全功能，还有一些内置的语法糖（比如在一行音乐代码前加上/就可以直接播放），这个编辑器的文件是musicpy editor.pyw，就在musicpy的代码文件夹里，打开前请先看read me first!.txt这个文件。wiki的介绍这个编辑器的章节的地址https://github.com/Rainbow-Dreamer/musicpy/wiki/How-to-use-musicpy-%E5%A6%82%E4%BD%95%E4%BD%BF%E7%94%A8musicpy

**Comment by mnixry** [comment]
其实增加一个Jupyter Notebook的支持也不失为一个好的方案

**Comment by oxygen-dioxide** [comment]
> 其实增加一个Jupyter Notebook的支持也不失为一个好的方案

附议，很多时候需要和matplotlib等其他库一起使用，而大部分库都适配Jupyter Notebook
