### ISSUE TITLE
速查表在 readthedocs 网页端的排版问题 | Layout Problem of Cheat Sheet on Readthedocs Web Pages

### ISSUE THREAD

**Issue by HairlessVillager** [Rainbow-Dreamer/musicpy#61]
如图，在页面加载完毕后，无论是中文版还是英文版页面，速查表均会出现排版问题，具体表现为表格宽度过宽，导致表格无法一次性显示水平方向上的所有内容，需要通过滑动页面**最下方**的滑条才能浏览，非常不方便。

[![QQ截图20230907220726.png](https://x.imgs.ovh/x/2023/09/07/64f9db4cca39c.png)](https://x.imgs.ovh/x/2023/09/07/64f9db4cca39c.png)
[![QQ截图20230907220234.png](https://x.imgs.ovh/x/2023/09/07/64f9db4d4d8ba.png)](https://x.imgs.ovh/x/2023/09/07/64f9db4d4d8ba.png)

**Comment by Rainbow-Dreamer** [comment]
感谢反馈，现在换了个主题，可以修复此问题
