### ISSUE TITLE
建议修改错别字

### ISSUE THREAD

**Issue by NKID00** [Rainbow-Dreamer/musicpy#8]
inputs_text 的 text：`清在这里输入` -> `请在这里输入`

**Comment by Rainbow-Dreamer** [comment]
感谢反馈，会去改正的，之后文本编辑器还会加入字体的类型与字体大小的选择以及语法高亮。

**Comment by Rainbow-Dreamer** [comment]
你的pull request已经接受，感谢你的改进！
